# Generated by Django 4.2.7 on 2026-01-08 12:15

from django.db import migrations, models


def migrate_to_email_primary_key(apps, schema_editor):
    """
    Custom migration function to change primary key from id to email.
    This handles MySQL's constraints properly by doing operations in the correct order.
    """
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("SHOW TABLES LIKE 'leads'")
        if not cursor.fetchone():
            return  # Table doesn't exist yet
        
        # Step 1: Ensure email is NOT NULL and add unique constraint
        try:
            cursor.execute("ALTER TABLE leads MODIFY email VARCHAR(254) NOT NULL")
        except Exception:
            pass  # Already NOT NULL
        
        try:
            cursor.execute("ALTER TABLE leads ADD UNIQUE KEY unique_email (email)")
        except Exception:
            pass  # Unique constraint already exists
        
        # Step 2: Drop the old primary key constraint (if id is the primary key)
        try:
            cursor.execute("ALTER TABLE leads DROP PRIMARY KEY")
        except Exception as e:
            # Primary key might not exist or already dropped
            pass
        
        # Step 3: Make email the primary key
        try:
            cursor.execute("ALTER TABLE leads ADD PRIMARY KEY (email)")
        except Exception as e:
            # Might already be primary key
            pass
        
        # Step 4: Remove auto_increment from id column (if it exists)
        try:
            cursor.execute("ALTER TABLE leads MODIFY id INT NOT NULL")
        except Exception:
            pass  # Column might not exist or already modified
        
        # Step 5: Drop the id column
        try:
            cursor.execute("ALTER TABLE leads DROP COLUMN id")
        except Exception as e:
            # Column might not exist
            pass


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: restore id as primary key.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW TABLES LIKE 'leads'")
        if not cursor.fetchone():
            return
        
        # Drop email primary key
        try:
            cursor.execute("ALTER TABLE leads DROP PRIMARY KEY")
        except Exception:
            pass
        
        # Add id column back
        try:
            cursor.execute("ALTER TABLE leads ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY FIRST")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        # Use RunPython to handle database changes manually for MySQL
        migrations.RunPython(
            migrate_to_email_primary_key,
            reverse_migration,
        ),
        # Update Django's model state to match database
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='id',
        ),
    ]
